#
# KubOS Linux
# Copyright (C) 2017 Kubos Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For the moment, there are no differences between the MBM2 and a regular
# Beaglebone Black, so just use the existing code for it.

obj-y	+= ../../ti/am335x/board.o
obj-y	+= ../../ti/am335x/mux.o
obj-y	+= ../../ti/common/board_detect.o


